# Generated by Django 5.2.6 on 2025-10-12 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_asset_quantity_asset_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.staff'),
        ),
    ]
