# Generated by Django 5.2.6 on 2025-10-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_asset_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
