# Generated by Django 5.2.7 on 2025-11-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_asset_brand_alter_asset_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='emai',
            new_name='email',
        ),
    ]
