# Generated by Django 5.2.7 on 2025-11-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_emai_staff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
