# Generated by Django 5.2.7 on 2025-11-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_staff_email_alter_staff_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
