# Generated by Django 5.2.7 on 2025-11-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_order_order_id_order_status_alter_asset_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='asset',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
