# Generated by Django 5.2.7 on 2025-11-11 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_order_quantity_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='date_expected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'Information Technology'), ('HR', 'Human Resource'), ('ADMIN', 'Administrative'), ('FINANCE', 'Accounting & Finance'), ('OPS', 'Operational')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='instruction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Delivered', 'Delivered'), ('In Transit', 'In Transit'), ('Processing', 'Processing'), ('Pending', 'Pending')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.order')),
            ],
        ),
    ]
