# Generated by Django 5.2.7 on 2026-01-26 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_rename_order_id_order_track_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='location',
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('IE', 'IT Equipment'), ('MB', 'Mobiles Devices'), ('OF', 'Office Furnitures'), ('OS', 'Office Supplies'), ('NE', 'Network Equipment'), ('SL', 'Software & Licenses'), ('EE', 'Electrical Equipement'), ('SS', 'Security Systems'), ('MISC', 'Miscellaneous')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_purchase',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_warranty',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='dashboard.staff'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Under Maintenance', 'Under Maintenance'), ('Retired', 'Retired')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='track_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Delivered', 'Delivered'), ('In Transit', 'In Transit'), ('Pending', 'Pending')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
