# Generated by Django 5.2.7 on 2026-02-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_staff_location_alter_asset_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-date_purchase']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_ordered']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-start_date']},
        ),
    ]
