# Generated by Django 5.2.7 on 2026-02-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='related_object_type',
        ),
        migrations.AddField(
            model_name='activity',
            name='related_object_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='related_object_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
